steps:
  # pull the container image if it is already built
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'docker pull gcr.io/$gcp-deploy-345516/appcicd:latest || exit 0'
  # build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$gcp-deploy-345516/appcicd:latest'
      - '-t'
      - 'gcr.io/$gcp-deploy-345516/appcicd:$COMMIT_SHA'
      - '--cache-from'
      - 'gcr.io/$gcp-deploy-345516/appcicd:latest'
      - '.'
  # push the container image to Container Registry with all tags
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$gcp-deploy-345516/appcicd'
  # deploy container image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'appml'
      - '--image'
      - 'gcr.io/$gcp-deploy-345516/appcicd:latest'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
